### ISSUE TITLE
[BUG] Conditions

### ISSUE THREAD

**Issue by ssg3Davins** [Larkinabout/fvtt-token-action-hud-dnd5e#50]
Conditions are not displaying active status, and they don't apply effects either, like Dfred's. They are working fine on the tokenHUD.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.5.

**Comment by ssg3Davins** [comment]
The Dfred effects still won't apply. In _toggleCondition the effect is always null, but I don't know how this function works, so no other idea.

**Comment by Larkinabout** [comment]
Can you capture a video of the issue please as I've tested with Dfred's Convenient Effects and both effects and conditions/status effects are applying as expected.

**Comment by ssg3Davins** [comment]
https://youtu.be/B14QWI0B1j4

**Comment by Larkinabout** [comment]
I think this may have been a Dfred's Convenient Effects issue, but I've tested it as working in Token Action HUD D&D 5e 1.4.7.
