### ISSUE TITLE
[BUG] Spells from Magic Items do not show up in HUD for non-caster character

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#73]
**Describe the bug**
I am using the Magic Items 2 module. This fighter character has a wand of magic missile. The magic missile spell is shown on her sheet but is not visible in the token action hud.

Using current versions of dnd5e system and all modules.

<img width="868" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/72390280/88c151f9-57e5-434b-b9e0-99c8bc9be81f">
<img width="691" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/72390280/7ba1c628-7b8f-45e9-95c3-60631be480e6">
<img width="576" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/72390280/2f815c0c-0b24-4e3b-86f1-0f94ece06d04">

**Comment by RavenknightDM** [comment]
Would love to see this added again. I know it used to work with the hud.

**Comment by Larkinabout** [comment]
Fixed in 1.5.3.

**Comment by YenBenGrey** [comment]
I know this is closed, but it is still not working for me. 
Magic Items 4.1.1
DND v3.1.1
Foundry 11 315
TAH 1.5.4
TAH DND5e 1.5.3

Please help. 

https://discord.com/channels/170995199584108546/722566083499786352/1222865680005599242

**Comment by Larkinabout** [comment]
Do you have the Magic Items group added to the HUD?

**Comment by YenBenGrey** [comment]
Hello, 

I am not sure I know how to do that? 

I unlocked one characters HUD and was able to add 'Magic Items' as a header, but not sure how to put magic items in there?
There is nothing there when I hover over it.

**Comment by YenBenGrey** [comment]
Ok no worries I have figured it out :-)
